### ISSUE TITLE
PostgreSQLを作成する

### ISSUE THREAD

**Issue by takumashiraki** [takumashiraki/weather-report#5]
PostgreSQL
[DBを作成](https://zenn.dev/eguchi244_dev/articles/sql-postresql-install-20230620)

**Comment by takumashiraki** [comment]
### PostgreSQLを起動する

```console
brew services start postgresql 
==> Successfully started `postgresql@14` (label: homebrew.mxcl.postgresql@14)
```

### データーベースの一覧を確認する

```console
psql -l
                                    List of databases
   Name    |     Owner     | Encoding | Collate | Ctype |        Access privileges
-----------+---------------+----------+---------+-------+---------------------------------
 postgres  | shirakitakuma | UTF8     | C       | C     |
 template0 | shirakitakuma | UTF8     | C       | C     | =c/shirakitakuma               +
           |               |          |         |       | shirakitakuma=CTc/shirakitakuma
 template1 | shirakitakuma | UTF8     | C       | C     | =c/shirakitakuma               +
           |               |          |         |       | shirakitakuma=CTc/shirakitakuma
```

**Comment by takumashiraki** [comment]
### docker-compose.yml
作成
```yaml
version: "3"

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      # DBファイルのパスをvolumeにマウントして永続化
      - db-store:/var/lib/postgresql/data
      # scriptディレクトリの.sqlファイルでSQLを実行
      - ./script:/docker-entrypoint-initdb.d
    environment:
      # スーパーユーザのユーザ名
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weather_report_db
volumes:
  db-store:
```

PostgreSQLのDBコンテナを作成
```console
docker-compose up -d
docker ps
CONTAINER ID   IMAGE         COMMAND                   CREATED          STATUS          PORTS                                       NAMES
c6ecb955b818   postgres:14   "docker-entrypoint.s…"   22 minutes ago   Up 22 minutes   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   postgres
```
